{% set name = "pyqode.python" %}
{% set version = "4.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a29eb274f2f5a4e25daf4ab7fae42c539d72d480acdcb8bb9ae8ac6a669948ec
  patches:
    - pyflakes25_fix.patch
    - version_setup.py.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - docutils
    - jedi
    - pycodestyle
    - pip
    - pyflakes
    - pyqode.core
    - pyqode.qt
    - python >=3.6
    - setuptools
  run:
    - docutils
    - jedi
    - pycodestyle
    - pyflakes
    - pyqode.core
    - pyqode.qt
    - python >=3.6
    - setuptools

test:
  imports:
    - pyqode
    - pyqode.python
    - pyqode.python._forms
    - pyqode.python.backend
    - pyqode.python.managers
    - pyqode.python.modes
    - pyqode.python.panels
    - pyqode.python.widgets
  requires:
    - pyqt

about:
  home: https://github.com/pyQode/pyqode.python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Adds python support to pyqode.core
  doc_url: https://github.com/pyQode/pyQode/wiki
  dev_url: https://github.com/pyQode/pyQode

extra:
  recipe-maintainers:
    - ericpre
