travis:
  secure:
    BINSTAR_TOKEN: Lv8CQmreqHS+0cxXnPyNixUwnoJzzp0AYxBplB1WmReXAKE9QVXx/Eu2aGE/5l2BtSmwbIwOHlo0hXeVEfxNfDeK0emNQfuqwKR/ZSRuAFiQsuthSxozd/s2xJkApOsjsZCV6uzOSC8N1Xx4AQMOjL7qnwx0hl5na8hGPDpyz8PD3mUIez5He4HX5CWChP7zlyBpRoyFHwK1zYPpN1Cxfe3RbPzxTNvhVDfiTCPiN5HQlnZ04PhKb/zSbDhbaAuDeF/38dOPK7/mBkhc6jPPBa+mqVsCGDjY8fOsS4VIj96DQw+YRybXVf2EtL9sxj1TEzSlamdHlaZrPukQQS8aFWTER8GBBhL1kYI3wVbWWGs/KyjIaW81XeE1pjKpLG2GJ7UUUkh5iAXEc7n8LrMW7Smw10JNMU507e0ZhFM/xTkBfCNyoZO9GZ5SJrKL78n5Kly/A8fCoAwQtYcSEJkLdcHC53pSx6llTKsBdFz69ghuIVzjeC8fkMbiEUpTwWxlh7mw2n/O2hNpUbNlM3tqbwCYio8SrZkynTvcQGrg6XuCMkdpssZEg/KtUXgvx2W9QaFXfBUcKH7GTK+xowXNSbfMttYHbBTyVUyOyPCjAp67ej7p4/yUV+NdW7kwuZlmTtgRMi3s2dol+xG56ZDrrWIlZs1ejsS2AX6OVRlotA8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
